### ISSUE TITLE
Projects List

### ISSUE THREAD

**Issue by eduskx** [eduskx/hammerhart#1]
## Value proposition
As a DIY enthusiast
I want to browse a list of projects,
In order to I can discover new DIY projects to undertake.
## Description
![image](https://github.com/user-attachments/assets/53f8bf31-1ee7-4bd5-956d-0eb26144c3b8)
## Acceptance criteria
- The homepage displays a list of DIY projects.
- The projects list is headlined with its purpose.
- Each project listing includes:
  - Project title
  - Project image
  - Project complexity
- The list supports vertical scrolling to accommodate multiple entries.
## Tasks
- [x] Create feature branch `feature/projects-list`
- [x] Inspect and adapt the example data in the [assets folder](./assets/projects.json)
  - [x] Add an `imageUrl` for each project, for example from [unsplash.com](https://unsplash.com)
- [x] Add "Header" component with headline (h1)
- [x] create "ProjectCard" component with title, image and complexity
- [x] create "ProjectsList" component, fetch the data (projects) and map through the projects
