### ISSUE TITLE
Edit modal

### ISSUE THREAD

**Issue by Kevin-Stein** [eduskx/hammerhart#11]
## Value proposition
As a DIY enthusiast
I want to have a button to edit the details page
In order to increase the user experience
## Description
![Image](https://github.com/user-attachments/assets/fbaef38b-dce3-467c-a4eb-47f7b2294986)
## Acceptance criteria
- Clicking the edit button opens a pop-up modal showing the prefilled edit Form.
- Cancel button and clicking outside allows to close the edit Form.
- Submit button saves the changes and closes the edit Form.

## Tasks
- [x] Create a `feature/edit-modal` branch
- [x] Replace StyledEditLink with StyledEditButton
    - [x] Change edit page to `EditForm` component
    - [x]  Write an onClick-function to open the `EditForm` component as modal
    - [x] blurr/darken the background
- [x] Re-use `Modal` components
