### ISSUE TITLE
Project Details

### ISSUE THREAD

**Issue by MoritzBhl** [eduskx/hammerhart#2]
## Value proposition
As a DIY enthusiast
I want to access detailed information about each project,
In order to I can effectively utilise the information to complete my DIY projects.
## Description
![Image](https://github.com/user-attachments/assets/96a855ec-1afe-42d1-a740-f21169d07ba9)
## Acceptance criteria
- Each project in the projects list has a link to a details page.
- Each details page contains:
  - Project title
  - Project image
  - Project description
  - Project complexity
  - Project duration
  - Project materials list
  - Project steps list
- The detailed view includes a “back” link, allowing users to easily navigate back to the list of projects.
## Tasks
- [x] Create feature branch `feature/project-details`
- [x] Create a pages/[id]/index.js page which shows according details
- [x] Wrap every ProjectCard in a Link
- [x] Create a Link to get back to the projects list
- [x] Create a details list including: title, image, tag, description, duration
- [x] Create a materials list with all materials you need for the project
- [x] Create a instructions list which describes step-by-step instructions (ordered list)

**Comment by MerleMak** [comment]
you will need to create a dynamic page for each project in the project list like [id].jsx in the pages folder, please add this step to the tasks :)

**Comment by MerleMak** [comment]
you don't need to fetch the data with swr yet, because you are still working with a data array in your project at this point :)
