### ISSUE TITLE
Create Project

### ISSUE THREAD

**Issue by MoritzBhl** [eduskx/hammerhart#3]
## Value proposition
As a DIY enthusiast
I want to create and store new projects,
In order to I can keep track of my DIY projects.
## Description
![Image](https://github.com/user-attachments/assets/7a930469-6225-4bb1-a6b7-95f7679cf7fa)
## Acceptance criteria
- A form for adding projects is displayed at the top of the homepage.
- The form is headlined with its purpose.
- The form must include labelled fields for:
  - Project title
  - Project description
  - Project complexity
  - Project duration
  - Project materials (dynamic form fields)
  - Project steps (dynamic form fields)
- The following fields are mandatory:
  - Project title
  - Project complexity
  - Project duration
- The complexity is selected via a dropdown menu with the following options: Beginner, Intermediate, or Advanced.
- The complexity dropdown must include a default option, “Please select a complexity level”, and necessitates a selection.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new project is added to the top of the projects list.
## Tasks
- [x] Create feature branch `feature/create-project`
- [x] Create state with useState: [projects, setProjects] = useState(initialProjects) in app.js
- [x] Create a "Form" component which contains: title, image, description, complexity (drop down menu), duration, materials and instructions
    - [x] Create DynamicInput components for materials and instructions (steps)
- [x] When clicking submit, add the new project to newProjects state and display it on top of the list (setProjects([newProject, ...projects])
- [x] Add a "clear" button to reset the form
- [x] Use LocalStorageState to save all projects in local storage

> 💡 It is not yet possible to add images at this stage. For this reason, a placeholder image should be saved when creating a new project.

> 💡 You can accommodate multiple materials and steps by using dynamic form fields, which allow additional input fields to be added as needed.
