### ISSUE TITLE
Pop-up modal for creating projects

### ISSUE THREAD

**Issue by eduskx** [eduskx/hammerhart#36]
## Value proposition
As a DIY enthusiast
I want to have a button to open the create form
In order to increase the user experience
## Description

![Image](https://github.com/user-attachments/assets/f9ea3f1b-efb0-4bfc-b18a-706cbb2fb0a3)

## Acceptance criteria
- The button must be fixed.
- Clicking the button opens a pop-up modal showing the Form.
- Cancel button and clicking outside allows to close the Form.

## Tasks
- [x] Create a `feature/create-modal` branch
- [x] Create `AddButton` component
    - [x] Write a onClick-function to open the `Form` component as modal
    - [x] blurr/darken the background
- [x]  Re-use `Modal` components
