### ISSUE TITLE
Collapsible lists

### ISSUE THREAD

**Issue by eduskx** [eduskx/hammerhart#37]
## Value proposition
As a DIY enthusiast
I want to expand and collapse lists in the details page
In order to hide or show certain information as I need it
## Description

![Image](https://github.com/user-attachments/assets/89beece0-60dd-402a-898f-09df02e8b7fe)

## Acceptance criteria
- Show drop down menu for materials and steps on details page
- Display all list items correctly.
- Show a message when list is empty.
- Show Drop Down menu only if content is available.
## Tasks
- [ ] Create `feature/collapsible-lists` branch
- [ ] Install/Import needed package: https://www.npmjs.com/package/react-collapsible
- [ ] Wrap the content with the "Collapsible" component
