### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by eduskx** [eduskx/hammerhart#38]
## Value proposition
As a DIY enthusiast 
I want to upload my own images
In order to have a matching picture of my project
## Description

![Image](https://github.com/user-attachments/assets/de2ef980-1df7-449f-a3d7-ad8a33752c20)

## Acceptance criteria
- [ ] I want a placeholder picture if no image is uploaded.
- [ ] When i click the Image-button i can select a picture from my local device.
- [ ] Show error message if i use the wrong file format.
## Tasks
- [ ] Create feature/Image-upload branch
- [ ] Use Cloudinary for storage. 
- [ ] Setting up the project via Web Capstone Docs.
https://web-capstone-docs.neuefische.de/additional-libraries/cloudinary
- [ ] Create a "ImageUpload" component
   - [ ] Create a handleSubmit function and get its data. 
   - [ ] Create an API Route (e.g. /pages/api/upload/index.js).
   - [ ] Write a handler function to send our image file to Cloudinary. 
- [ ] Replace URL Input field with a new Upload Button in the "Form" component

**Comment by NikRoe** [comment]
LGTM
