### ISSUE TITLE
Project Notes

### ISSUE THREAD

**Issue by eduskx** [eduskx/hammerhart#39]
## Value proposition
As a DIY enthusiast
I want to write notes on the Details Page
In order to remember ideas/problems.
## Description

![Image](https://github.com/user-attachments/assets/688f6517-d0f8-451d-bc46-b5d0f2b84815)

## Acceptance criteria
- [ ] Default content should be "Notes.." if the content is empty.
- [ ] Text should be displayed at the end of the Details Page
- [ ] Notes can be edited directly on the detailspage.
## Tasks
- [ ] Create "feature/project-notes" branch
- [ ] Create a useState for Notes.
- [ ] Create a "Notes" component
    - [ ] Textarea with default content "Notes..."
    - [ ] Edit button
- [ ] Create a Edit function.
- [ ] Insert new "notes" object inside projects array.
- [ ] Render "Notes" component on Details Page.

**Comment by Roland-Hufnagel** [comment]
LGTM except of the third AC: What you like is not the point 😂 Better: 'Notes can be edited directly on the detailspage.'
