### ISSUE TITLE
Delete Project

### ISSUE THREAD

**Issue by MoritzBhl** [eduskx/hammerhart#4]
## Value proposition
As a DIY enthusiast
I want to be able to delete projects that are no longer relevant,
In order to I can maintain a clean and organised projects list, ensuring it’s always up to date.
## Description
![Image](https://github.com/user-attachments/assets/1a8a1d8c-6597-4770-902e-e7674fd8d0cd)
## Acceptance criteria
- Each project details view includes an easily accessible delete option.
- Clicking the delete option triggers a confirmation dialog.
- The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- The dialog includes options for both confirming the deletion and cancelling the action.
- The cancellation option allows the user to back out of the deletion process if selected by mistake or if they change their mind.
- Upon confirming the deletion, the user is immediately redirected to the overview of all projects, and the project is removed from the list.
- If all projects are deleted, a message appears indicating that there are no projects and providing an option to add new ones.
## Tasks
- [x] Create feature branch `feature/delete-project`
- [x] Create a "DeleteButton" component to delete the selected project 
    - [x] Render DeleteButton on details page
    - [x] DeleteButton gets the following props: projects, setProjects
    - [x] Write a function to delete the project from projects (hint: setProjects(projects.filter((project) => project.id !== idToRemove));
- [x] Create a confirmation dialog when clicking the delete button with cancel and confirm button (hint: alert)
- [x] Clicking the confirm button returns to list page with router.push()
- [x] Show message when project list is empty (hint: array.length === 0)
