### ISSUE TITLE
Header with Logo and menu

### ISSUE THREAD

**Issue by Kevin-Stein** [eduskx/hammerhart#41]
## Value proposition
As a DIY enthusiast
I want to have a header
In order to see the logo and the burger menu
## Description
![Image](https://github.com/user-attachments/assets/6ebb4d03-b9ec-455b-a2f3-0d0b8d105d8e)
## Acceptance criteria
- [ ] Display the app´s logo on the left hand side, clicking on the Logo redirect to the Homepage
- [ ] Display the burger menu icon on the right hand side (Mobile)
- [ ] If you click on the icon you can choose between the bookmark Page and Social Media Links (X, facebook, instagram and youtube)

## Tasks
- [ ] Create a feature/header branch
- [ ] Go to the `Header` Component and create a div for the header
- [ ] Within the div create a h1, Image for the logo and a Image within a button 
        for the burger menu
- [ ] Write a toggle function for opening and closing the icon

**Comment by NikRoe** [comment]
Hi there,

please be more specific in the AC as to what the options are that are being displayed after having clicked on the icon.

**Comment by NikRoe** [comment]
LGTM
