### ISSUE TITLE
Project of the Day Component

### ISSUE THREAD

**Issue by Kevin-Stein** [eduskx/hammerhart#42]
## Value proposition
As a DIY enthusiast
I want to show a random-project on the top of the project-list
in order to get new inspiration.
## Description

![Image](https://github.com/user-attachments/assets/e26d5746-bcf0-4c5f-86e7-0925813167d6)

## Acceptance criteria
- [ ] The View of the Random-Project have to be larger than the other projects.
- [ ] The access to the DetailsPage by clicking the project should be available.
- [ ] The option to set the Bookmark-State is also available.
## Tasks
- [ ] Create feature branch feature/random-project
- [ ] Create a random-function to generate a random-project and display it on the top of the ProjecstList-Page.
