### ISSUE TITLE
add checkboxes for materials list and Instructions/steps

### ISSUE THREAD

**Issue by Kevin-Stein** [eduskx/hammerhart#49]
## Value proposition
As a DIY enthusiast
I want to add checkboxes for materials and steps
In order to tick off every step I did / material I have 
## Description
![Image](https://github.com/user-attachments/assets/54cedfe3-e369-4e1c-ae65-edde2158022b)
## Acceptance criteria
- [ ] Checkboxes to tick off "every" step and material 
- [ ] This is a purely visual feature to help the user track their progress and materials. 
## Tasks
- [x] Change list-style-type to none
- [x] Insert `<Input type=checkboxes>` inside the mapped list items for materials and Steps

**Comment by e-Steffen** [comment]
Looks good at all. Only two things to consider:
1. The acceptance criteria should describe the things out of users perspective. 
2. Instead of list-style "none" could "type="checkbox"" be an option? With this one the materials and steps could be checked (done) or unchecked (open).
