### ISSUE TITLE
Update Project

### ISSUE THREAD

**Issue by MoritzBhl** [eduskx/hammerhart#5]
## Value proposition
As a DIY enthusiast
I want to update the details of existing projects,
In order to they reflect the most accurate and relevant information.
## Description
![Image](https://github.com/user-attachments/assets/7550f98f-af53-48b2-be5e-7a4596822e53)
## Acceptance criteria
- Each project’s details page includes an easily accessible edit option.
- Clicking the edit option opens a new page with a form pre-filled with the project’s existing details for modification.
- The form allows for edits to all project details, including:
  - Project title
  - Project description
  - Project complexity
  - Project duration
  - Project materials (dynamic form fields)
  - Project steps (dynamic form fields)
- The following fields are mandatory:
  - Project title
  - Project complexity
  - Project duration
- The form section includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- Submissions with empty mandatory fields are blocked, with validation messages indicating the missing required fields.
- Upon confirming the save, the user is immediately redirected to the details page of the edited project, and the changes are saved and reflected.
## Tasks
- [x] Create feature branch `feature/edit-project` 
- [x] Create pages/[id]/edit.js page 
    - [x] use useRouter to get id from query
    - [x] import data from projects.json
    - [x] find id from projects.json that matches id from query
    - [x] Render Form with prop: defaultData={project}
- [x] Create "EditButton" component to edit existing entry 
    - [x]  on click: redirect to pages/[id]/edit.js page 
- [x] Render EditButton on details page (pages/[id]/index.js)
    - [x] Create save and cancel buttons
        - [x] Clicking cancel button redirects to details page (hint: router.back)
        - [x] Write a function that updates object when clicking on save

> 💡 It is not yet possible to edit images at this stage.

> 💡 You can accommodate multiple materials and steps by using dynamic form fields, which allow additional input fields to be added as needed.
