### ISSUE TITLE
Image Upload Preview

### ISSUE THREAD

**Issue by MoritzBhl** [eduskx/hammerhart#51]
## Value proposition
As a DIY enthusiast
I want to display the selected image
In order to feedback if the upload worked
## Description
![Image](https://github.com/user-attachments/assets/2c086cc5-76cd-4b76-a426-97b509514b1f)
## Acceptance criteria
- [ ] The image preview is displayed next to the upload button
## Tasks
- [x] Create a feature/image-preview branch
- [x] Add an useState [image, setImage]
- [x] Write a function which refreshes the setImage inside the form
- [x] Render the image below the Upload button

**Comment by Roland-Hufnagel** [comment]
LGTM
