### ISSUE TITLE
Description text counter

### ISSUE THREAD

**Issue by Kevin-Stein** [eduskx/hammerhart#52]
## Value proposition
As a DIY enthusiast 
I want to capture and limit the characters for textfields.
In order to to prevent a too long text.
## Description

![Image](https://github.com/user-attachments/assets/567cd6ba-3ff7-421d-9c04-ee985a921038)

## Acceptance criteria

- [ ] An Overview about the the allowed quantity (max. 250 characters) of the remaining characters during creating or editing a description-content
- [ ] Each quantity of the input-character should be subtract from the specific max-input-character. 
- [ ] When the maximum number of characters is reached, the counter is coloured red and a shake effect is executed twice.

## Tasks
- [x] Create feature branch feature/text-counter
- [x] Define max. quantity of the characters by adding the attribut "maxLength" for the description-content
- [x] Create the function handleChangeLimit to monitor the length of the input-content
- [x] Create a css style that colours counter red and creates a shaking effect when the maximum number of characters is reached.

**Comment by NikRoe** [comment]
Hi there,

nice start!

Please be more specific in your Acceptance Criteria when it comes to the behaviour after having implemented the new feature.
Some question you could answer here are: What happens if I reach the maximum amount of characters? Will there be a message? If so, where? 

Cheers ✌

**Comment by NikRoe** [comment]
LGTM
