### ISSUE TITLE
Global Styling Index

### ISSUE THREAD

**Issue by Kevin-Stein** [eduskx/hammerhart#53]
## Value proposition
As a DIY enthusiast
I want  a simple and modern Design
In order to have a better User Experience.
## Description

![Image](https://github.com/user-attachments/assets/d2f1e5cf-ecc5-4a37-bd83-7f2e0cad116e)

## Acceptance criteria
- [ ] Define all colours, fonts and everything that is used multiple times in the global styles as variables.
- [x] The cards should have a hover effect that rotates the content slightly and the complexity colour is displayed
- [x] The menu icon disappears in the tablet and desktop version.
## Tasks
- [x] Create a `styling/global-styling` branch.
- [x] Create font and color variables in the GlobalStyles.
