### ISSUE TITLE
Text formatting Options for Notes and Description

### ISSUE THREAD

**Issue by Kevin-Stein** [eduskx/hammerhart#54]
## Value proposition
As a DIY enthusiast
I want simple toolbar for textareas.
In order to simple style my text.
## Description

![Image](https://github.com/user-attachments/assets/8d2bd397-4910-452f-98ad-b84a22949888)

## Acceptance criteria
- [x] Simple toolbar for textareas (bold, italic, undeline, textcolor etc)
- [x] You can choose several options at the same time.
- [x] Only the marked text should be changed
- [x] All Options are toggle Buttons.
## Tasks
- [x] Create feature/text-toolbar branch
- [x] Install PrimeReact 
- [x] Install quill
- [x] create useState "value" for the onChange function
- [x] Import the "Editor" component from "primereact/editor"
- [x] Replace the textareas with the "Editor" component.

**Comment by NikRoe** [comment]
Hi there,

please be more specific in your Acceptance Criteria when it comes to the actual behaviour of your toolbar after implementation.
Some questions you could and should answer here: Will clicking on one of the options change all of it? Can I select more than one option? Does double clicking toggle? etc.

Cheers ✌

**Comment by NikRoe** [comment]
LGTM
