### ISSUE TITLE
Bookmark Project

### ISSUE THREAD

**Issue by MoritzBhl** [eduskx/hammerhart#6]
## Value proposition
As a DIY enthusiast
I want to mark projects as favourites,
In order to I can quickly access and track the ones I am most interested in.
## Description
![Image](https://github.com/user-attachments/assets/bb943fe2-cd7b-42cc-9927-e629cd2c01b0)
## Acceptance criteria
- Each project includes a bookmark option, available on both the projects list and project details page.
- Clicking the bookmark button of an unbookmarked project adds it to the bookmarked list.
- Clicking the bookmark button of a bookmarked project removes it from the bookmarked list.
- The bookmarked projects are displayed on a separate list accessible via a new page dedicated to bookmarked projects.
- There is a clearly visible link on the homepage to navigate to the bookmarked projects page.
- There is a clearly visible link on the bookmarked projects page to navigate back to the homepage.
- Bookmarked projects are visually highlighted by a distinct bookmark icon colour to differentiate them from unbookmarked projects.
## Tasks
- [x] Create feature branch `feature/bookmark-project`
- [x] Create  isFavorite, setIsFavorite = useState(false)
- [x] add "isFavorite" key to initialData
- [x] add toggleFunction in _app.js
- [x] toggle between active and inactive style.
- [x] Create bookmark page and display all bookmarked Projects
- [x] Create "Bookmark" component and display on list page and details page
- [x] Create navigation bar component

**Comment by MerleMak** [comment]
you will definitely need a state where you safe all the favorites or enrich the original data array with a key "isFavorite"
