### ISSUE TITLE
Implement Improvements

### ISSUE THREAD

**Issue by eduskx** [eduskx/hammerhart#62]
## Value proposition
As a DIY enthusiast
I want no visual bugs in the app
In order to increase user experience

## Acceptance criteria
- Positioning of the buttons in the delete modal is correct
- Project notes are deleted from local storage after project is deleted

## Tasks
- [x] Create the improvement branch
- [x] Switch the positions of the Buttons in the delete-function
- [x] Change the Button-Text (Yes instead Delete and No instead Cancel)
- [x] Extend your delete-function to remove also the notes of a project.
