### ISSUE TITLE
Styling Bookmark Page

### ISSUE THREAD

**Issue by MoritzBhl** [eduskx/hammerhart#73]
## Value proposition
As a DIY enthusiast
I want a simple and modern Design
In order to have a better User Experience.
## Description
![Image](https://github.com/user-attachments/assets/9dfc44af-23b6-43bd-bd44-4691963c7563)
![Image](https://github.com/user-attachments/assets/44e2c5b9-dbf2-4f93-947f-6a25ed1f9965)
![Image](https://github.com/user-attachments/assets/2c72740d-ea53-4335-924b-61396626aae7)
## Acceptance criteria
- [ ] The cards should have a hover effect that rotates the content slightly and the complexity colour is displayed
- [ ] The menu icon disappears in the tablet and desktop version and the serach bar moves to the header
- [ ] The colors should be added as in the images shown as well as the positioning of the individual elements
- [ ] The App should be responisve for mobile, tablet and desktop

## Tasks
- [ ] Create a styling/bookmark branch.
- [ ] Style the page based on the images

**Comment by SylvieDoumet** [comment]
Your value proposition is very flue - your US is named : bookmark - this should be refleceted in a concrete way in your value proposition, like : 
As a user, I want to bookmark my favorite ..., so that I can easily access them later in a visually appealing and user-friendly interface.

Users can browse through various ... on the platform. Given the extensive list of ... available, users might want to save or bookmark certain ... for quick reference later. This feature should be seamlessly integrated into the current design, maintaining a modern, clean, and intuitive user experience.
