### ISSUE TITLE
Style Details Page

### ISSUE THREAD

**Issue by MoritzBhl** [eduskx/hammerhart#75]
## Value proposition
As a DIY enthusiast
I want a simple and modern Design
In order to have a better User Experience.
## Description
![Image](https://github.com/user-attachments/assets/cba56f48-1cfc-46d2-8cf3-4354ff84ece1)
![Image](https://github.com/user-attachments/assets/0e7b01da-b696-44df-8c6e-7e170dc7d116)
## Acceptance criteria
- [ ] The details page should be adapted for the tablet and desktop version using media queries
- [ ] The colors should be added as in the images shown as well as the positioning of the individual elements
- [ ] The details page has a fixed header and footer and a scrollable main
## Tasks
- [ ] Create a styling/details-page branch
- [ ] Style the page based on the images
- [ ] Use media queries for Tablet and Desktop Version

**Comment by Roland-Hufnagel** [comment]
`The details page should be stretched for the tablet and desktop version` What does this mean? The page is stretched by default. Please define more precisely what should change in tablet/desktop view. Your wireframe seems to show the mobile view. You could add a few tasks as well (eg using mediaqueries,...)

**Comment by Roland-Hufnagel** [comment]
Again: Please describe HOW the details page should be adapted to the tablet or desktop view. The use of mediaqueries is an implementation detail and can be a part of the tasks.
